<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="networks" nsURI="http://www.example.org/networks" nsPrefix="networks">
  <eClassifiers xsi:type="ecore:EClass" name="Network">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="networkAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" upperBound="-1"
        eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internet" eType="#//Internet"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Internet"/>
  <eClassifiers xsi:type="ecore:EClass" name="Device" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Computer" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EReference" name="computerSwitch" eType="#//Switch"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EReference" name="switchRouter" eType="#//Router"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Server" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverSwitch" eType="#//Switch"
        derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Router" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EReference" name="routerInternet" eType="#//Internet"
        derived="true"/>
  </eClassifiers>
</ecore:EPackage>
